# Github action to run the moocounter script daily
name: Daily Moo Counter Simulation
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync

      - name: Run Moo Counter Simulation
        run: uv run moo_counter --puzzle live --iterations 10000

      - uses: actions/upload-artifact@v4
        with:
          name: moo_count_histogram
          path: moo_count_histogram.json

